### ISSUE TITLE
APIError: Code#100

### ISSUE THREAD

**Issue by ilyamixaltik** [xTCry/nestjs-vk#6]
При отправке сообщения (метод ctx.send(string) или ctx.reply(string)) - выдает ошибку 'APIError: Code #100 - One of the parameters specified was missing or invalid: type not integer'.

Сообщение отправляется, все ок. Но появляется ошибка

**Comment by ilyamixaltik** [comment]
![image](https://user-images.githubusercontent.com/49319539/173589369-99a1fe48-fd50-49de-a753-97cbb44fb920.png)
![image](https://user-images.githubusercontent.com/49319539/173589583-9065f1e0-b7c6-4064-8f8d-3a9ad76c44fc.png)

**Comment by xTCry** [comment]
Думаю, в этой проблеме, за длительное время моего ответа, ты уже разобрался

Скорее всего это из-за кода на 13 строке `VkSvcController`, там не надо юзать `retuen` при использовании `ctx.send`.
Если в слушателе события вернуть какое-то значение, то выполнится `ctx.send`.

https://github.com/xTCry/nestjs-vk/blob/90750d3c3bd50f3455ebc4474fcbf8cb392a8112/lib/services/listeners-explorer.service.ts#L194-L200
