### ISSUE TITLE
Scenes support

### ISSUE THREAD

**Issue by pavlyutkin** [xTCry/nestjs-vk#7]
Why aren't scenes supported?

**Comment by kosheeta** [comment]
Scenes are supported but don't have documentation.

https://github.com/xTCry/nestjs-vk/commit/c25e0be142a6d63845e23881e5f37e3b5edde157

**Comment by xTCry** [comment]
The README file has been updated 000a11cf14d028ae9f40dbea9cc2950a0d2b1b46

**Comment by pavlyutkin** [comment]
Thanks!
